name: C/C++ CI

on:
  push:
    branches: [master]

jobs:
  clean-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        name: Delete Older Releases
        with:
          keep_latest: 0
          repo: ""
          delete_tags: true
          delete_tag_pattern: "cse-tactics"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-x64-build:
    needs: [clean-releases]
    runs-on: ubuntu-latest
    container:
      image: tsukisuperior/sdl2-docker:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Compile Test
        run: cd $GITHUB_WORKSPACE && mkdir build && cd build && cmake .. -DPLATFORM=LINUX-X64 && make
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cse-tactics-linux-x64
          release_name: Linux X64 Release
          draft: false
          prerelease: true
          body: |
            Check commits for changes
    
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/cse-tactics
          asset_name: cse-tactics
          asset_content_type: application/zip

  linux-x86-build:
    needs: [clean-releases]
    runs-on: ubuntu-latest
    container:
      image: tsukisuperior/sdl2-docker:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Compile Test
        run: cd $GITHUB_WORKSPACE && mkdir build && cd build && cmake .. -DPLATFORM=LINUX-X64 && make
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cse-tactics-linux-x86
          release_name: Linux X86 Release
          draft: false
          prerelease: true
          body: |
            Check commits for changes

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/cse-tactics
          asset_name: cse-tactics
          asset_content_type: application/zip

  windows-x86-build:
    needs: [clean-releases]
    runs-on: ubuntu-latest
    container:
      image: tsukisuperior/sdl2-docker:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Compile Test
        run: cd $GITHUB_WORKSPACE && mkdir build && cd build && cmake .. -DPLATFORM=WINDOWS-X86 && make
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cse-tactics-windows-x86
          release_name: Windows x86 Release
          draft: false
          prerelease: true
          body: |
            Check commits for changes
    
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/cse-tactics.exe
          asset_name: cse-tactics.exe
          asset_content_type: application/zip
          
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/contrib/sdl2/SDL2.dll
          asset_name: SDL2.dll
          asset_content_type: application/zip
  
  windows-x64-build:
    needs: [clean-releases]
    runs-on: ubuntu-latest
    container:
      image: tsukisuperior/sdl2-docker:latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: Compile Test
        run: cd $GITHUB_WORKSPACE && mkdir build && cd build && cmake .. -DPLATFORM=WINDOWS-X64 && make
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: cse-tactics-windows-x64
          release_name: Windows x64 Release
          draft: false
          prerelease: true
          body: |
            Check commits for changes
    
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/cse-tactics.exe
          asset_name: cse-tactics.exe
          asset_content_type: application/zip
  
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/contrib/sdl2/SDL2.dll
          asset_name: SDL2.dll
          asset_content_type: application/zip

